routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('roue/for/check/php/version/detail',function(){
	ob_start();
    phpinfo();
    return ob_get_clean();
});


// Route::get('/', function () {
//     return view('welcome');
// });
//Admin Routes//

 Route::get('Admin','Admin\AdminController@view');
 Route::resource('Admin/construction','Admin\ConstructionController');
 Route::resource('Admin/Architecture','Admin\ArchitectureController');
 Route::resource('Admin/Interior','Admin\InteriorController');
 Route::resource('Admin/TownPlaning','Admin\TownPlanningController');
 Route::resource('Admin/Landscape','Admin\LandscapeController');
 Route::get('/Admin/company-register','Admin\AdminController@companyprofile');

 Route::resource('admin/company','Admin\CompanyController');
 Route::resource('admin/company-profile-contact','Admin\CompanyProfileContactController');
 Route::resource('admin/company-profile','Admin\CompanyProfileController');
 Route::resource('admin/company-profile-gallery','Admin\CompanyProfileGalleryController');
Route::resource('admin/setting','Admin\WebsiteSettingController');
Route::resource('admin/gallery','Admin\GalleryCategoryController');
Route::resource('admin/gallarysub','Admin\GallerysubController');
Route::resource('admin/gimages','Admin\GalleryimagesController');
Route::resource('admin/sponseradd','Admin\SponserController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// web controller 
Route::post('naqsha-search','Website\HomeController@naqsha_search')->name('naqsha-search');
Route::get('/','Website\HomeController@index')->name('home.index');

Route::get('about-us','Website\HomeController@about')->name('home.about');
Route::get('term-condition','Website\HomeController@term_condition')->name('home.term.condition');
Route::get('faq','Website\HomeController@faq')->name('home.faq');
Route::get('blogs','Website\HomeController@blogs')->name('home.blogs');

Route::get('architecture','Website\HomeController@architecture')->name('home.architecture');
Route::get('construction','Website\HomeController@construction')->name('home.construction');
Route::get('interior','Website\HomeController@interior')->name('home.interior');
Route::get('landscape','Website\HomeController@landscape')->name('home.landscape');
Route::get('town-planner','Website\HomeController@town_planner')->name('home.town.planner');
Route::get('engineers','Website\HomeController@engineers')->name('home.engineers');



Route::get("gallery3d-type/{id}","Website\HomeController@gallery_type")->name('gallery.3d.type');
Route::get("gallery-images/{id}","Website\HomeController@kanal_2_residential")->name('kanal.2.residential');
Route::get("d3_evlevation","Website\HomeController@d3_evlevation")->name('d3.evlevation');
Route::get("one_kanal_house","Website\HomeController@one_kanal_house")->name('one.kanal.house');

Route::get("interior_gallery_type","Website\HomeController@interior_gallery_type")->name('interior.gallery.type');
Route::get("commercial_interior","Website\HomeController@commercial_interior")->name('commercial.interior');
Route::get("residential_interior","Website\HomeController@residential_interior")->name('residential.interior');
Route::get("landscap_gallery","Website\HomeController@landscap_gallery")->name('landscap.gallery');
Route::get("landscapes","Website\HomeController@landscapes")->name('landscapes');

Route::get('company-detail/{id}','Website\HomeController@company_detail')->name('company.detail');

Route::post('sendEmail','Website\HomeController@sendEmail')->name('sendEmail');

Route::post('forBusinessEmail','Website\HomeController@forBusinessEmail')->name('forBusinessEmail');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'companies';
    protected $primaryKey = 'id';

    protected $fillable = ['id','c_name','c_type','c_drawing_detail','c_profile_image'];

    function companyProfile()
    {
    	return $this->belongsTo('App\Models\Company','company_id');
    }

    public function companyProfileContactDetail(){
    	return $this->belongsTo('App\Models\CompanyProfileContactDetail','company_profile_id');
    }
}

app/companyprofile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Models\Company;
class companyprofile extends Model
{
    protected $table = 'companyprofiles';
    protected $primaryKey = 'id';

    protected $fillable = ['id','c_id','cp_slider_image','cp_about_us','c_profile_image'];

    function company()
    {
    	return $this->belongsTo('App\Models\Company','c_id');
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;


class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Company::paginate(20);
        return view('Admin.company.index', compact('company'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = new Company();
        $company->c_name = $request->c_name;
        $company->c_type = $request->c_type;
        $company->c_drawing_detail = $request->c_drawing_detail;

        if ($request->file('c_profile_image')) {
            $file = $request->c_profile_image;
            $extension = $file->getClientOriginalExtension();
            $filename = rand(11111, 99999) . '.' . $extension;
            $company->c_profile_image = $filename;
            $path = public_path('images/company_profile');
            $file->move($path, $filename);
        }
        $company->save();

        return redirect()->route('company.index');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('Admin.company.create', compact('company'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::find($id);
        $company->c_name = $request->c_name;
        $company->c_type = $request->c_type;
        $company->c_drawing_detail = $request->c_drawing_detail;

        if ($request->file('c_profile_image')) {
            $file = $request->c_profile_image;
            $extension = $file->getClientOriginalExtension();
            $filename = rand(11111, 99999) . '.' . $extension;
            $company->c_profile_image = $filename;
            $path = public_path('images/company_profile');
            $file->move($path, $filename);
        }

        $company->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id)->delete();
        return back()->with('message', 'Record deleted successfully ');
    }
}

app/Http/Controllers/Admin/CompanyProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\companyprofile;
use Illuminate\Support\Facades\Input;
use App\Models\Company;

class CompanyProfileController extends Controller
{
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $data['company_profile']=companyprofile::with('company')->paginate(20);
        //dd($data['company_profile']);
        return view('Admin.company.company-profile.index',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = Company::all();
        // dd($company);
        return view('Admin.company.company-profile.create',compact('company'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company_profile = new companyprofile();
        $company_profile->company_id = $request->company_id;

        if ($request->file('cp_slider_image')) {
            $file = $request->cp_slider_image;
            $extension = $file->getClientOriginalExtension();
            $filename = rand(11111, 99999) . '.' . $extension;
            $company_profile->cp_slider_image = $filename;
            $path = public_path('images/cp_slider_images');
            $file->move($path, $filename);
        }

        $company_profile->cp_about_us = $request->cp_about_us;
        $company_profile->save();
        return redirect()->route('company-profile.index');
        return back();  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::all();
        $company_profile = companyprofile::find($id);
        return view('Admin.company.company-profile.create',compact('company','company_profile'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company_profile = companyprofile::find($id);
        $company_profile->company_id = $request->company_id;

        if ($request->file('cp_slider_image')) {
            $file = $request->cp_slider_image;
            $extension = $file->getClientOriginalExtension();
            $filename = rand(11111, 99999) . '.' . $extension;
            $company_profile->cp_slider_image = $filename;
            $path = public_path('images/cp_slider_images');
            $file->move($path, $filename);
        }

        $company_profile->cp_about_us = $request->cp_about_us;
        $company_profile->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $arch = companyprofile::find($id)->delete();
        return back()->with('message','Record deleted successfully ');
    }
}

resources/views/Admin/company/company-profile/create.blade.php
@extends('Admin.admin-layout')

@push('css')
@endpush
@section('content')

<div class="container-fluid">
   <!-- BEGIN PAGE HEADER-->

   <!-- BEGIN PAGE CONTENT-->
   <div class="row-fluid">
      <div class="span12">
         <!-- BEGIN VALIDATION STATES-->
         <div class="widget red">
            <div class="widget-title">
               <h4><i class=" icon-key"></i> Company Profile </h4>
               <span class="tools">
               <a href="javascript:;" class="icon-chevron-down"></a>
               <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body form">
               <!-- BEGIN FORM-->
               @isset($company_profile)
                 <form  class="form-horizontal" method="post" action="{{ route('company-profile.update',$company_profile->id) }}" enctype="multipart/form-data">
                   @method('put')
               @else
               <form  class="form-horizontal" method="post" action="{{ route('company-profile.store') }}" enctype="multipart/form-data">
               @endisset 
                  @csrf
                  <div class="control-group success">
                     <label class="control-label" for="company_id">Company </label>
                     <div class="controls">
                        <select class="form-control span6" name="company_id" id="ccompany_id" required="">
                           <option value="">Please Select Company</option>
                           @foreach($company as $value)
                              <option value="{{ $value->id }}">{{ $value->c_name }}</option>
                           @endforeach
                        </select>
                     </div>
                  </div>
                  <div class="control-group error">
                     <label class="control-label" for="inputError">Company Profile Slider Image</label>
                     <div class="controls">
                        <input type="file" class="span6" id="inputError" name="cp_slider_image" name="cp_slider_image" required="">
                  
                     </div>
                  </div>
                  <div class="control-group error">
                     <label class="control-label" for="cp_about_us">About Us</label>
                     <div class="controls">
                        <textarea name="cp_about_us" id="cp_about_us" class="form-control" required=""></textarea>
                     </div>
                  </div>
                  
                  
                  <div class="form-actions">
                     <button type="submit" class="btn btn-success">
                        @isset($company_profile)
                           Update
                        @else 
                        Save
                        @endisset
                     </button>
                     <button type="button" class="btn">Cancel</button>
                  </div>
               </form>
               <!-- END FORM-->
            </div>
         </div>
         <!-- END VALIDATION STATES-->
      </div>
   </div>

</div>
@endsection

@push('js')
@endpush

resources/views/Admin/company/company-profile/index.blade.php
@extends('Admin.admin-layout')

@push('css')
<style type="text/css">
   .company-profile{
      max-width: 100px;
   }
</style>
@endpush
@section('content')

<div class="container-fluid">
   <!-- BEGIN PAGE HEADER-->   
  <br><br>
   <!-- BEGIN EDITABLE TABLE widget-->
   <div class="row-fluid">
      <div class="span12">
         <!-- BEGIN EXAMPLE TABLE widget-->
         <div class="widget purple">
            <div class="widget-title">
               <h4>Company Profile</h4>
               <span class="tools">
               <a href="javascript:;" class="icon-chevron-down"></a>
               <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body">
               <div>
                  <div class="clearfix">
                     <div class="btn-group">
                        <a href="{{ route('company-profile.create') }}" id="editable-sample_new" class="btn green">
                        Add New <i class="icon-plus"></i>
                        </a>
                     </div>
               
                  </div>
                  <div class="space15"></div>
                  <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                     <div class="row-fluid">
                        <div class="span6">
                           <div id="editable-sample_length" class="dataTables_length">
                              <label>
                                 <select size="1" name="editable-sample_length" aria-controls="editable-sample" class="xsmall">
                                    <option value="5" selected="selected">5</option>
                                    <option value="15">15</option>
                                    <option value="20">20</option>
                                    <option value="-1">All</option>
                                 </select>
                                 records per page
                              </label>
                           </div>
                        </div>
                        <div class="span6">
                           <div class="dataTables_filter" id="editable-sample_filter"><label>Search: <input type="text" aria-controls="editable-sample" class="medium"></label></div>
                        </div>
                     </div>
                     <table class="table table-striped table-hover table-bordered dataTable" id="editable-sample" aria-describedby="editable-sample_info">
                        <thead>
                           <tr role="row">
                              <th>#</th>
                              <th>Company</th>
                              <th >Slider Image</th>
                              <th>About Us</th>
                               
                              <th >Edit</th>
                              <th >Delete</th>
                           </tr>
                        </thead> 
                        <tbody role="alert" aria-live="polite" aria-relevant="all">
                               @foreach($company_profile as $index => $value)
                           <tr class="odd">
                              <td class="  sorting_1">{{ ++$index }}</td>
                              <td class=" ">{{ $value->company['c_name'] }}</td>

                              <td class=" ">
                                 <img src="{{ asset('images/cp_slider_images/'.$value->cp_slider_image) }}" 
                                        class="company-profile" style="width: 100px;" />
                                 </td>
                              <td class="center ">{{ $value->cp_about_us }}</td>
                              <td class=" "><a class="edit" href="{{ route('company-profile.edit',$value->id) }}">Edit</a></td>
                              <td class=" ">
                                               <a class="delete" href="javascript::void();" onclick="event.preventDefault();
                                                     document.getElementById('delete-company-profile-{{ $value->id }}').submit();">Delete</a>

                                                          <form id="delete-company-profile-{{ $value->id }}" action="{{ route('company-profile.destroy',$value->id) }}" method="POST" style="display: none;">
                                 @method('delete')
                                        @csrf
                                </form>
                                  
                              </td>
                           </tr>
                           @endforeach
                           
                        </tbody>
                     </table>
                     <div class="row-fluid">
                        <div class="span6">
                           <div class="dataTables_info" id="editable-sample_info">Showing 1 to 5 of 12 entries</div>
                        </div>
                        <div class="span6">
                           <div class="dataTables_paginate paging_bootstrap pagination">
                              <ul>
                                 <li class="prev disabled"><a href="#">← Prev</a></li>
                                 <li class="active"><a href="#">1</a></li>
                                 <li><a href="#">2</a></li>
                                 <li><a href="#">3</a></li>
                                 <li class="next"><a href="#">Next → </a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- END EXAMPLE TABLE widget-->
      </div>
   </div>
   <!-- END EDITABLE TABLE widget-->
</div>
@endsection

@push('js')
@endpush