routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('roue/for/check/php/version/detail',function(){
	ob_start();
    phpinfo();
    return ob_get_clean();
});


// Route::get('/', function () {
//     return view('welcome');
// });
//Admin Routes//

 Route::get('Admin','Admin\AdminController@view');
 Route::resource('Admin/construction','Admin\ConstructionController');
 Route::resource('Admin/Architecture','Admin\ArchitectureController');
 Route::resource('Admin/Interior','Admin\InteriorController');
 Route::resource('Admin/TownPlaning','Admin\TownPlanningController');
 Route::resource('Admin/Landscape','Admin\LandscapeController');
 Route::get('/Admin/company-register','Admin\AdminController@companyprofile');

 Route::resource('admin/company','Admin\CompanyController');
 Route::resource('admin/company-profile-contact','Admin\CompanyProfileContactController');
 Route::resource('admin/company-profile','Admin\CompanyProfileController');
 Route::resource('admin/company-profile-gallery','Admin\CompanyProfileGalleryController');
Route::resource('admin/setting','Admin\WebsiteSettingController');
Route::resource('admin/gallery','Admin\GalleryCategoryController');
Route::resource('admin/gallarysub','Admin\GallerysubController');
Route::resource('admin/gimages','Admin\GalleryimagesController');
Route::resource('admin/sponseradd','Admin\SponserController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// web controller 
Route::post('naqsha-search','Website\HomeController@naqsha_search')->name('naqsha-search');
Route::get('/','Website\HomeController@index')->name('home.index');

Route::get('about-us','Website\HomeController@about')->name('home.about');
Route::get('term-condition','Website\HomeController@term_condition')->name('home.term.condition');
Route::get('faq','Website\HomeController@faq')->name('home.faq');
Route::get('blogs','Website\HomeController@blogs')->name('home.blogs');

Route::get('architecture','Website\HomeController@architecture')->name('home.architecture');
Route::get('construction','Website\HomeController@construction')->name('home.construction');
Route::get('interior','Website\HomeController@interior')->name('home.interior');
Route::get('landscape','Website\HomeController@landscape')->name('home.landscape');
Route::get('town-planner','Website\HomeController@town_planner')->name('home.town.planner');
Route::get('engineers','Website\HomeController@engineers')->name('home.engineers');



Route::get("gallery3d-type/{id}","Website\HomeController@gallery_type")->name('gallery.3d.type');
Route::get("gallery-images/{id}","Website\HomeController@kanal_2_residential")->name('kanal.2.residential');
Route::get("d3_evlevation","Website\HomeController@d3_evlevation")->name('d3.evlevation');
Route::get("one_kanal_house","Website\HomeController@one_kanal_house")->name('one.kanal.house');

Route::get("interior_gallery_type","Website\HomeController@interior_gallery_type")->name('interior.gallery.type');
Route::get("commercial_interior","Website\HomeController@commercial_interior")->name('commercial.interior');
Route::get("residential_interior","Website\HomeController@residential_interior")->name('residential.interior');
Route::get("landscap_gallery","Website\HomeController@landscap_gallery")->name('landscap.gallery');
Route::get("landscapes","Website\HomeController@landscapes")->name('landscapes');

Route::get('company-detail/{id}','Website\HomeController@company_detail')->name('company.detail');

Route::post('sendEmail','Website\HomeController@sendEmail')->name('sendEmail');

Route::post('forBusinessEmail','Website\HomeController@forBusinessEmail')->name('forBusinessEmail');

resources/views/Admin/TownPlaning/add_townplanning.blade.php
@extends('Admin.admin-layout')

@push('css')
@endpush
@section('content')

<div class="container-fluid">
   <!-- BEGIN PAGE HEADER-->
   <div class="row-fluid">
 
   </div>
   <!-- END PAGE HEADER-->
   <!-- BEGIN PAGE CONTENT-->
   <div class="row-fluid">
      <div class="span12">
         <!-- BEGIN VALIDATION STATES-->
         <div class="widget red">
            <div class="widget-title">
               <h4><i class=" icon-key"></i> TownPlaning </h4>
               <span class="tools">
               <a href="javascript:;" class="icon-chevron-down"></a>
               <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body form">
               <!-- BEGIN FORM-->
                  @if(isset($arch) && !empty($arch))
                  <form  class="form-horizontal" method="post" action="{{ route('TownPlaning.update',$arch->id) }}">
                     @method('put')
               @else

               <form  class="form-horizontal" method="post" action="{{ route('TownPlaning.store') }}">
                   @endif
                  @csrf
                 <div class="control-group success">
                     <label class="control-label" for="c_id">Company </label>
                     <div class="controls">
                        <select class="span6 form-control" name="company_id" id="c_id" required="">
                           <option value="">Please Select Company</option>
                           @foreach($company as $value)
                              <option value="{{ $value->id }}" @if(isset($arch) && isset($arch) && $value->id = $arch->company_id) selected="selected" @endif>{{ $value->c_name }}</option>
                           @endforeach
                        </select>
                     </div>
                  </div>
                  <div class="control-group error">
                     <label class="control-label" for="inputError">town_location</label>
                     <div class="controls">
                          <select name="town_location" class="form-control">
                                        <option value="">Please select Plot Location</option>
                                        <option value="Jinnah Colony, Faisalabad">Jinnah Colony, Faisalabad</option>
                                        <option value="Batala Colony, Faisalabad">Batala Colony, Faisalabad</option>
                                        <option value="DC Colony, Gujranwala">DC Colony, Gujranwala</option>
                                        <option value="Rahwali, Gujranwala">Rahwali, Gujranwala</option>
                                        <option value="Canal View, Gujranwala">Canal View, Gujranwala</option>
                                        <option value="City Housing Society, Gujranwala">City Housing Society, Gujranwala</option>
                                        <option value="Affandi colony, Islamabad">Affandi colony, Islamabad</option>
                                        <option value="Burma Town, Islamabad">Burma Town, Islamabad</option>
                                        <option value="Garden town, Islamabad">Garden town, Islamabad</option>
                                        <option value="Jagoit, Islamabad">Jagoit, Islamabad</option>
                                        <option value="Saddar, Islamabad">Saddar, Islamabad</option>
                                        <option value="Sector E-11, Islamabad">Sector E-11, Islamabad</option>
                                        <option value="Sector F-11, Islamabad">Sector F-11, Islamabad</option>
                                        <option value="Sector F-7, Islamabad">Sector F-7, Islamabad</option>
                                    </select>
                       
                  
                     </div>
                  </div>
                  <div class="control-group error">
                     <label class="control-label" for="inputError">covered_area</label>
                     <div class="controls">
                        <select name="covered_area" class="form-control">
                                            <option value="">Please select no of floor</option>
                                            <option value="1000">1000</option>

                                        </select>
                      
                       
                     </div>
                  </div>
                   <div class="control-group error">
                     <label class="control-label" for="inputError">rate_sqft</label>
                     <div class="controls">
                          <select name="rate_sqft" class="form-control">
                                            <option value="">Please select Rate</option>
                                            <option value="5 Marla">5 Marla</option>
                                            <option value="10 Marla">10 Marla</option>
                                            <option value="1 kanal">1 kanal</option>
                                            <option value="2 kanal">2 kanal</option>

                                        </select>
                      
                        
                     </div>
                  </div>
                   <div class="control-group error">
                     <label class="control-label" for="inputError">total</label>
                     <div class="controls">
                            <select name="   total" class="form-control">
                                            <option value="">Please select Type</option>
                                            <option value="Residential">Residential </option>
                                            <option value="Commercial">Commercial</option>

                                        </select>
                       
                        
                     </div>
                  </div>
                   <div class="control-group error">
                     <label class="control-label" for="inputError">Professional Location</label>
                     <div class="controls">
                        <select name="professional_location" class="form-control">
                                            <option value="">Please select Professional location</option>
                                            <option value="Quaid-e-Azam Industrial Estate, Lahore">Quaid-e-Azam Industrial Estate, Lahore</option>
                                            <option value="Royal Orchard, Multan">Royal Orchard, Multan</option>
                                            <option value="Shah Rukn-e-Alam Colony, Multan">Shah Rukn-e-Alam Colony, Multan</option>
                                            <option value="Model Town, Multan">Model Town, Multan</option>
                                            <option value="Chowk Shaheedan, Multan">Chowk Shaheedan, Multan</option>
                                        </select>
                        
                        
                     </div>
                  </div>
                  
                   <div class="control-group error">
                     <label class="control-label" for="inputError">details</label>
                     <div class="controls">
                        <input type="text" class="span6" id="inputError" name="details" required="" @if(isset($arch->details) && !empty($arch->details)) value="{{ $arch->details }}" @endif>
                        
                     </div>
                  </div>
                     <div class="control-group error">
                     <label class="control-label" for="inputError">get_quotation</label>
                     <div class="controls">
                        <input type="text" class="span6" id="inputError" name="get_quotation" required="" @if(isset($arch->get_quotation) && !empty($arch->get_quotation)) value="{{ $arch->get_quotation }}" @endif>
                        
                     </div>
                  </div>
                               
                  <div class="form-actions">
                     <button type="submit" class="btn btn-success">Save</button>
                     <button type="button" class="btn">Cancel</button>
                  </div>
               </form>
               <!-- END FORM-->
            </div>
         </div>
         <!-- END VALIDATION STATES-->
      </div>
   </div>

</div>
@endsection

@push('js')
@endpush

resources/views/Admin/TownPlaning/index.blade.php
@extends('Admin.admin-layout')

@push('css')
@endpush
@section('content')
<div class="container-fluid">
   <!-- BEGIN PAGE HEADER-->   
   <div class="row-fluid">
      <div class="span12">
         <!-- BEGIN THEME CUSTOMIZER-->
         <div id="theme-change" class="hidden-phone">
            <i class="icon-cogs"></i>
            <span class="settings">
            <span class="text">Theme Color:</span>
            <span class="colors">
            <span class="color-default" data-style="default"></span>
            <span class="color-green" data-style="green"></span>
            <span class="color-gray" data-style="gray"></span>
            <span class="color-purple" data-style="purple"></span>
            <span class="color-red" data-style="red"></span>
            </span>
            </span>
         </div>
         <!-- END THEME CUSTOMIZER-->
         <!-- BEGIN PAGE TITLE & BREADCRUMB-->
         <h3 class="page-title">
            Editable Table
         </h3>
         <ul class="breadcrumb">
            <li>
               <a href="#">Home</a>
               <span class="divider">/</span>
            </li>
            <li>
               <a href="#">Data Table</a>
               <span class="divider">/</span>
            </li>
            <li class="active">
               Editable Table
            </li>
            <li class="pull-right search-wrap">
               <form action="http://thevectorlab.net/metrolab/search_result.html" class="hidden-phone">
                  <div class="input-append search-input-area">
                     <input class="" id="appendedInputButton" type="text">
                     <button class="btn" type="button"><i class="icon-search"></i> </button>
                  </div>
               </form>
            </li>
         </ul>
         <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
   </div>
   <!-- END PAGE HEADER-->
   <!-- BEGIN EDITABLE TABLE widget-->
   <div class="row-fluid">
      <div class="span12">
         <!-- BEGIN EXAMPLE TABLE widget-->
         <div class="widget purple">
            <div class="widget-title">
               <h4><i class="icon-reorder"></i> Editable Table</h4>
               <span class="tools">
               <a href="javascript:;" class="icon-chevron-down"></a>
               <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body">
               <div>
                  <div class="clearfix">
                     <div class="btn-group">
                        <a href="{{ route('TownPlaning.create') }}" id="editable-sample_new" class="btn green">
                        Add New <i class="icon-plus"></i>
                        </a>
                     </div>
                     <div class="btn-group pull-right">
                        <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right">
                           <li><a href="#">Print</a></li>
                           <li><a href="#">Save as PDF</a></li>
                           <li><a href="#">Export to Excel</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="space15"></div>
                  <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                     <div class="row-fluid">
                        <div class="span6">
                           <div id="editable-sample_length" class="dataTables_length">
                              <label>
                                 <select size="1" name="editable-sample_length" aria-controls="editable-sample" class="xsmall">
                                    <option value="5" selected="selected">5</option>
                                    <option value="15">15</option>
                                    <option value="20">20</option>
                                    <option value="-1">All</option>
                                 </select>
                                 records per page
                              </label>
                           </div>
                        </div>
                        <div class="span6">
                           <div class="dataTables_filter" id="editable-sample_filter"><label>Search: <input type="text" aria-controls="editable-sample" class="medium"></label></div>
                        </div>
                     </div>
                     <table class="table table-striped table-hover table-bordered dataTable" id="editable-sample" aria-describedby="editable-sample_info">
                        <thead>
                           <tr role="row">
                              <th class="sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="Username" style="width: 193px;">subcribed_company</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Full Name: activate to sort column ascending" style="width: 288px;">town_location</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Points: activate to sort column ascending" style="width: 128px;">covered_area</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Notes: activate to sort column ascending" style="width: 184px;">rate_sqft</th>
                               <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Notes: activate to sort column ascending" style="width: 184px;">total</th>
                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Notes: activate to sort column ascending" style="width: 184px;">details</th>
                                  <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Notes: activate to sort column ascending" style="width: 184px;">get_quotation</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Edit: activate to sort column ascending" style="width: 89px;">Edit</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Delete: activate to sort column ascending" style="width: 129px;">Delete</th>
                           </tr>
                        </thead>
                        <tbody role="alert" aria-live="polite" aria-relevant="all">
                               @foreach($cc as $index => $value)
                           <tr class="odd">
                              <td class="  sorting_1">@if($value->company){{ $value->company->c_name }}@endif</td>
                              <td class=" ">{{ $value->town_location }}</td>
                              <td class=" ">{{ $value->covered_area }}</td>
                            <td class="center ">{{ $value->covered_area}}</td>
                            <td class="center ">{{ $value->rate_sqft }}</td>
                            <td class="center ">{{ $value->total }}</td>
                            <td class="center ">{{ $value->details }}</td>
                            <td class="center ">{{ $value->get_quotation }}</td>
                            
                              <td class=" "><a class="edit" href="{{ route('TownPlaning.edit',$value->id) }}">Edit</a></td>
                                <td class=" ">
                                 <a class="delete" href="javascript::void();" onclick="event.preventDefault();
                                                     document.getElementById('delete-arch-{{ $value->id }}').submit();">
                                                  Delete
                                 </a>
                                <form id="delete-arch-{{ $value->id }}" action="{{ route('TownPlaning.destroy',$value->id) }}" method="POST" style="display: none;">
                                 @method('delete')
                                        @csrf
                                </form>
                              </td>
                           </tr>
                          @endforeach
                       
                         </tbody>
                     </table>
                     <div class="row-fluid">
                        <div class="span6">
                           <div class="dataTables_info" id="editable-sample_info">Showing 1 to 5 of 12 entries</div>
                        </div>
                        <div class="span6">
                           <div class="dataTables_paginate paging_bootstrap pagination">
                              <ul>
                                 <li class="prev disabled"><a href="#">← Prev</a></li>
                                 <li class="active"><a href="#">1</a></li>
                                 <li><a href="#">2</a></li>
                                 <li><a href="#">3</a></li>
                                 <li class="next"><a href="#">Next → </a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- END EXAMPLE TABLE widget-->
      </div>
   </div>
   <!-- END EDITABLE TABLE widget-->
</div>
@endsection

@push('js')
@endpush