routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('roue/for/check/php/version/detail',function(){
	ob_start();
    phpinfo();
    return ob_get_clean();
});


// Route::get('/', function () {
//     return view('welcome');
// });
//Admin Routes//

 Route::get('Admin','Admin\AdminController@view');
 Route::resource('Admin/construction','Admin\ConstructionController');
 Route::resource('Admin/Architecture','Admin\ArchitectureController');
 Route::resource('Admin/Interior','Admin\InteriorController');
 Route::resource('Admin/TownPlaning','Admin\TownPlanningController');
 Route::resource('Admin/Landscape','Admin\LandscapeController');
 Route::get('/Admin/company-register','Admin\AdminController@companyprofile');

 Route::resource('admin/company','Admin\CompanyController');
 Route::resource('admin/company-profile-contact','Admin\CompanyProfileContactController');
 Route::resource('admin/company-profile','Admin\CompanyProfileController');
 Route::resource('admin/company-profile-gallery','Admin\CompanyProfileGalleryController');
Route::resource('admin/setting','Admin\WebsiteSettingController');
Route::resource('admin/gallery','Admin\GalleryCategoryController');
Route::resource('admin/gallarysub','Admin\GallerysubController');
Route::resource('admin/gimages','Admin\GalleryimagesController');
Route::resource('admin/sponseradd','Admin\SponserController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// web controller 
Route::post('naqsha-search','Website\HomeController@naqsha_search')->name('naqsha-search');
Route::get('/','Website\HomeController@index')->name('home.index');

Route::get('about-us','Website\HomeController@about')->name('home.about');
Route::get('term-condition','Website\HomeController@term_condition')->name('home.term.condition');
Route::get('faq','Website\HomeController@faq')->name('home.faq');
Route::get('blogs','Website\HomeController@blogs')->name('home.blogs');

Route::get('architecture','Website\HomeController@architecture')->name('home.architecture');
Route::get('construction','Website\HomeController@construction')->name('home.construction');
Route::get('interior','Website\HomeController@interior')->name('home.interior');
Route::get('landscape','Website\HomeController@landscape')->name('home.landscape');
Route::get('town-planner','Website\HomeController@town_planner')->name('home.town.planner');
Route::get('engineers','Website\HomeController@engineers')->name('home.engineers');



Route::get("gallery3d-type/{id}","Website\HomeController@gallery_type")->name('gallery.3d.type');
Route::get("gallery-images/{id}","Website\HomeController@kanal_2_residential")->name('kanal.2.residential');
Route::get("d3_evlevation","Website\HomeController@d3_evlevation")->name('d3.evlevation');
Route::get("one_kanal_house","Website\HomeController@one_kanal_house")->name('one.kanal.house');

Route::get("interior_gallery_type","Website\HomeController@interior_gallery_type")->name('interior.gallery.type');
Route::get("commercial_interior","Website\HomeController@commercial_interior")->name('commercial.interior');
Route::get("residential_interior","Website\HomeController@residential_interior")->name('residential.interior');
Route::get("landscap_gallery","Website\HomeController@landscap_gallery")->name('landscap.gallery');
Route::get("landscapes","Website\HomeController@landscapes")->name('landscapes');

Route::get('company-detail/{id}','Website\HomeController@company_detail')->name('company.detail');

Route::post('sendEmail','Website\HomeController@sendEmail')->name('sendEmail');

Route::post('forBusinessEmail','Website\HomeController@forBusinessEmail')->name('forBusinessEmail');

resources/views/Admin/includes/footer.blade.php
<div id="footer">
   2013 &copy; Metro Lab Dashboard.
</div>


   <script src="{{ asset('public/admin-assets')}}/js/jquery-1.8.3.min.js"></script>
   <script src="{{ asset('public/admin-assets')}}/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script type="text/javascript" src="{{ asset('public/admin-assets')}}/assets/jquery-slimscroll/jquery-ui-1.9.2.custom.min.js"></script>
   <script type="text/javascript" src="{{ asset('public/admin-assets')}}/assets/jquery-slimscroll/jquery.slimscroll.min.js"></script>
   <script src="{{ asset('public/admin-assets')}}/assets/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
   <script src="{{ asset('public/admin-assets')}}/assets/bootstrap/js/bootstrap.min.js"></script>


   <script src="{{ asset('public/admin-assets')}}/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js" type="text/javascript"></script>
   <script src="{{ asset('public/admin-assets')}}/js/jquery.sparkline.js" type="text/javascript"></script>
   <script src="{{ asset('public/admin-assets')}}/assets/chart-master/Chart.js"></script>
   <script src="{{ asset('public/admin-assets')}}/js/jquery.scrollTo.min.js"></script>


   <!--common script for all pages-->
   <script src="{{ asset('public/admin-assets')}}/js/common-scripts.js"></script>

   <!--script for this page only-->

   <script src="{{ asset('public/admin-assets')}}/js/easy-pie-chart.js"></script>
   <script src="{{ asset('public/admin-assets')}}/js/sparkline-chart.js"></script>
   <script src="{{ asset('public/admin-assets')}}/js/home-page-calender.js"></script>
   <script src="{{ asset('public/admin-assets')}}/js/home-chartjs.js"></script>

   <!-- END JAVASCRIPTS -->   
</body>

</html>

resources/views/Admin/includes/head.blade.php
<!DOCTYPE html>
<head>
   <meta charset="utf-8" />
   <title>Naqsha Ghar</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="Mosaddek" name="author" />
   <link href="{{ asset('public/admin-assets')}}/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="{{ asset('public/admin-assets')}}/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="{{ asset('public/admin-assets')}}/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="{{ asset('public/admin-assets')}}/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="{{ asset('public/admin-assets')}}/css/style.css" rel="stylesheet" />
   <link href="{{ asset('public/admin-assets')}}/css/style-responsive.css" rel="stylesheet" />
   <link href="{{ asset('public/admin-assets')}}/css/style-default.css" rel="stylesheet" id="style_color" />
   <link href="{{asset('public/admin-assets')}}/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
   <link href="{{ asset('public/admin-assets')}}/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>
</head>

resources/views/Admin/includes/header.blade.php
<!-- BEGIN BODY -->
<body class="fixed-top">
   <!-- BEGIN HEADER -->
   <div id="header" class="navbar navbar-inverse navbar-fixed-top">
       <!-- BEGIN TOP NAVIGATION BAR -->
       <div class="navbar-inner">
           <div class="container-fluid">
               <!--BEGIN SIDEBAR TOGGLE-->
               <div class="sidebar-toggle-box hidden-phone">
                   <div class="icon-reorder tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
               </div>
               <!--END SIDEBAR TOGGLE-->
               <!-- BEGIN LOGO -->
               <a class="brand" href="{{url('Admin')}}">
                   <img src="{{ asset('public/assets/images/naqshagharlogo.png') }}" alt="" />
               </a>
               <!-- END LOGO -->
               <!-- BEGIN RESPONSIVE MENU TOGGLER -->
               <a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="arrow"></span>
               </a>
               <!-- END RESPONSIVE MENU TOGGLER -->
               <div id="top_menu" class="nav notify-row">
                 
               </div>
               <!-- END  NOTIFICATION -->
               <div class="top-nav ">
                   <ul class="nav pull-right top-menu" >
                       <!-- BEGIN SUPPORT -->
                       
                       <!-- END SUPPORT -->
                       <!-- BEGIN USER LOGIN DROPDOWN -->
                       <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                               <img src="img/avatar1_small.jpg" alt="">
                               <span class="username">{{ Auth::user()->name }}</span>
                               <b class="caret"></b>
                           </a>
                           <ul class="dropdown-menu extended logout">
                               <!-- <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                               <li><a href="#"><i class="icon-cog"></i> My Settings</a></li> -->
                               <li>
                                <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                  <i class="icon-key"></i> Log Out
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                </form>

                                </li>
                           </ul>
                       </li>
                       <!-- END USER LOGIN DROPDOWN -->
                   </ul>
                   <!-- END TOP NAVIGATION MENU -->
               </div>
           </div>
       </div>
       <!-- END TOP NAVIGATION BAR -->
   </div>
   <!-- END HEADER -->
<div id="container" class="row-fluid">
  <!-- BEGIN PAGE -->
  @include('Admin.includes.sidebar')  
<div id="main-content">
   <!-- BEGIN PAGE CONTAINER-->
   <div class="container-fluid">

  

  @yield('content')
</div>
</div>
</div>

resources/views/Admin/includes/page-content.blade.php
 <div class="row-fluid">
                <!--BEGIN METRO STATES-->
                <div class="metro-nav">
                    <div class="metro-nav-block nav-block-orange">
                        <a data-original-title="" href="#">
                            <i class="icon-user"></i>
                            <div class="info">321</div>
                            <div class="status">New User</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-olive">
                        <a data-original-title="" href="#">
                            <i class="icon-tags"></i>
                            <div class="info">+970</div>
                            <div class="status">Sales</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-yellow">
                        <a data-original-title="" href="#">
                            <i class="icon-comments-alt"></i>
                            <div class="info">49</div>
                            <div class="status">Comments</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-green double">
                        <a data-original-title="" href="#">
                            <i class="icon-eye-open"></i>
                            <div class="info">+897</div>
                            <div class="status">Unique Visitor</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-red">
                        <a data-original-title="" href="#">
                            <i class="icon-bar-chart"></i>
                            <div class="info">+288</div>
                            <div class="status">Update</div>
                        </a>
                    </div>
                </div>
                <div class="metro-nav">
                    <div class="metro-nav-block nav-light-purple">
                        <a data-original-title="" href="#">
                            <i class="icon-shopping-cart"></i>
                            <div class="info">29</div>
                            <div class="status">New Order</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-light-blue double">
                        <a data-original-title="" href="#">
                            <i class="icon-tasks"></i>
                            <div class="info">$37624</div>
                            <div class="status">Stock</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-light-green">
                        <a data-original-title="" href="#">
                            <i class="icon-envelope"></i>
                            <div class="info">123</div>
                            <div class="status">Messages</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-light-brown">
                        <a data-original-title="" href="#">
                            <i class="icon-remove-sign"></i>
                            <div class="info">34</div>
                            <div class="status">Cancelled</div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey ">
                        <a data-original-title="" href="#">
                            <i class="icon-external-link"></i>
                            <div class="info">$53412</div>
                            <div class="status">Total Profit</div>
                        </a>
                    </div>
                </div>
                <div class="space10"></div>
                <!--END METRO STATES-->
            </div>

resources/views/Admin/includes/sidebar.blade.php
<style type="text/css">
   .p-9{
      padding: 9px;
   }
</style>
<!-- BEGIN SIDEBAR -->
<div class="sidebar-scroll">
   <div id="sidebar" class="nav-collapse collapse">
      <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
      <div class="navbar-inverse">
         <form class="navbar-search visible-phone">
            <input type="text" class="search-query" placeholder="Search" />
         </form>
      </div>
      <!-- END RESPONSIVE QUICK SEARCH FORM -->
      <!-- BEGIN SIDEBAR MENU -->
      <ul class="sidebar-menu">
         <li class="sub-menu @if(Request::is('Admin')) active @endif">
            <a class="p-9" href="{{url('Admin')}}">
            <i class="icon-dashboard"></i>
            <span>Dashboard</span>
            </a>
         </li>
         <li class="sub-menu @if(Request::is('Admin/Architecture') || Request::is('Admin/Architecture/*') || Request::is('Admin/construction') || Request::is('Admin/construction/*') || Request::is('Admin/Interior') || Request::is('Admin/Interior/*') || Request::is('Admin/TownPlaning') || Request::is('Admin/TownPlaning/*') || Request::is('Admin/Landscape') || Request::is('Admin/Landscape/*')) active open @endif">
            <a href="javascript:;" class="p-9">
            <i class="icon-book"></i>
            <span>Main Menu</span>
            <span class="arrow"></span>
            </a>
            <ul class="sub">
               <li class="@if(Request::is('Admin/Architecture') || Request::is('Admin/Architecture/*')) active @endif">
                  <a class="p-9" href="{{url('Admin/Architecture')}}">
                     Architecture
                  </a>
               </li>
               <li class="@if(Request::is('Admin/construction') || Request::is('Admin/construction/*')) active @endif">
                  <a class="p-9" href="{{url('Admin/construction')}}">
                     Construction
                  </a>
               </li>
               <li class="@if(Request::is('Admin/Interior') || Request::is('Admin/Interior/*')) active @endif">
                  <a class="p-9" href="{{url('Admin/Interior')}}">
                     Interior
                  </a>
               </li>
               <li class="@if(Request::is('Admin/Landscape') || Request::is('Admin/Landscape/*')) active @endif">
                  <a class="p-9" href="{{url('Admin/Landscape')}}">
                     LandScape
                  </a>
               </li>
               <li class="@if(Request::is('Admin/TownPlaning') || Request::is('Admin/TownPlaning/*')) active @endif">
                  <a class="p-9" href="{{url('Admin/TownPlaning')}}">
                     Town Planiing
                  </a>
               </li>
             
            </ul>
         </li>

          <li class="sub-menu  @if(Request::is('admin/company') || Request::is('admin/company/*') || Request::is('admin/company-profile') || Request::is('admin/company-profile/*') || Request::is('admin/company-profile-contact') || Request::is('admin/company-profile-contact/*') || Request::is('admin/company-profile-gallery') || Request::is('admin/company-profile-gallery/*')) active open @endif">
            <a href="javascript:;" class="p-9">
            <i class="icon-book"></i>
            <span>Company</span>
            <span class="arrow"></span>
            </a>
            <ul class="sub">
               <li  class="@if(Request::is('admin/company') || Request::is('admin/company/*')) active @endif">
                  <a class="p-9" href="{{ route('company.index') }}">
                     Compnay
                  </a>
               </li>
               <li class="@if(Request::is('admin/company-profile') || Request::is('admin/company-profile/*')) active @endif">
                  <a class="p-9" href="{{ route('company-profile.index') }}">
                     Company Profile
                  </a>
               </li>
               <li class="@if(Request::is('admin/company-profile-contact') || Request::is('admin/company-profile-contact/*')) active @endif">
                  <a class="p-9" href="{{ route('company-profile-contact.index') }}">
                     Compnay profile Contact
                  </a>
               </li>
               <li class="@if(Request::is('admin/company-profile-gallery') || Request::is('admin/company-profile-gallery/*')) active @endif">
                  <a class="p-9" href="{{ route('company-profile-gallery.index') }}">
                  Company Profile Gallery 
               </a>
            </li>
            </ul>
         </li>
           <li class="sub-menu  @if(Request::is('admin/setting') || Request::is('admin/setting/*')) active open @endif">
            <a href="javascript:;" class="p-9">
            <i class="icon-book"></i>
            <span>Setting</span>
            <span class="arrow"></span>
            </a>
            <ul class="sub">
               <li  class="@if(Request::is('admin/setting') || Request::is('admin/setting/*')) active @endif">
                  <a class="p-9" href="{{ route('setting.index') }}">
                     Setting
                  </a>
               </li>
              
            </ul>
         </li>

         <li class="sub-menu  @if(Request::is('admin/sponseradd') || Request::is('admin/sponseradd/*')|| Request::is('admin/gimages') || Request::is('admin/gimages/*')|| Request::is('admin/gallery') || Request::is('admin/gallery/*')|| Request::is('admin/gallarysub') || Request::is('admin/gallarysub/*')) active open @endif">
            <a href="javascript:;" class="p-9">
            <i class="icon-book"></i>
            <span>Gallery</span>
            <span class="arrow"></span>
            </a>
            <ul class="sub">
               <li  class="@if(Request::is('admin/gallery') || Request::is('admin/gallery/*')) active @endif">
                  <a class="p-9" href="{{ route('gallery.index') }}">
                     Gallery
                  </a>
               </li>

               <li  class="@if(Request::is('admin/gallarysub') || Request::is('admin/gallarysub/*')) active @endif">
                  <a class="p-9" href="{{ route('gallarysub.index') }}">
                     Gallery Subcategory
                  </a>
               </li>
               <li  class="@if(Request::is('admin/gimages') || Request::is('admin/gimages/*')) active @endif">
                  <a class="p-9" href="{{ route('gimages.index') }}">
                     Gallery Images
                  </a>
               </li>

               <li  class="@if(Request::is('admin/sponseradd') || Request::is('admin/sponseradd/*')) active @endif">
                  <a class="p-9" href="{{ route('sponseradd.index') }}">
                     Sponser Add
                  </a>
               </li>
              
            </ul>
         </li>
      </ul>
      <!-- END SIDEBAR MENU -->
   </div>
</div>
<!-- END SIDEBAR -->